name: Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Main metrics
      uses: lowlighter/metrics@v3.34
      with:
        filename: github-metrics-main.svg
        token: ${{ secrets.METRICS_TOKEN }}
        user: castledking
        template: classic
        base: header, activity, community, repositories, metadata
        plugin_languages: yes
        plugin_repositories: yes
        plugin_stars: yes
        plugin_topics: yes
    
    - name: Calendar metrics
      uses: lowlighter/metrics@v3.34
      with:
        filename: github-metrics-calendar.svg
        token: ${{ secrets.METRICS_TOKEN }}
        user: castledking
        base: ""
        plugin_isocalendar: yes
